# Generated by Django 2.2 on 2021-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
